import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, Bot, CheckCircle2, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
import { dash, EmptyState, LoadingState, periodTitle, useDashboard } from "@/lib/dashboard-api";
export const Route = createFileRoute("/ai")({ head: () => ({ meta: [{ title: "Análise IA — CAG Expo Center Norte" }] }), component: AIPage });
function AIPage(){const{data,loading,error}=useDashboard();if(loading)return <LoadingState/>;if(error||!data)return <EmptyState message={error||"Sem dados para exibir."}/>;const ia=data.assistente_ia||{};const diag=ia.diagnosticos||[];const resumo=ia.resumo_periodo||{};return <div className="space-y-5"><section className="relative overflow-hidden rounded-[2rem] border border-status-ai/25 bg-[linear-gradient(135deg,rgba(88,28,135,0.22),rgba(15,23,42,0.92))] p-6"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_0%,rgba(168,85,247,0.22),transparent_42%)]"/><div className="relative"><div className="inline-flex items-center gap-2 rounded-full border border-status-ai/35 bg-status-ai/10 px-3 py-1 text-[11px] font-bold uppercase tracking-[0.18em] text-status-ai"><Sparkles className="h-3.5 w-3.5"/> Assistente de Manutenção</div><h1 className="mt-4 font-display text-3xl font-bold">Análise IA</h1><p className="mt-2 text-sm text-muted-foreground">Análise operacional do período {periodTitle(data)}.</p></div></section><section className="grid gap-4 lg:grid-cols-3"><Card title="Equipamentos em atenção" value={(resumo.equipamentos_em_atencao||[]).length}/><Card title="Ocorrências principais" value={(resumo.principais_ocorrencias||[]).length}/><Card title="Diagnósticos" value={diag.length}/></section><section className="grid gap-4 xl:grid-cols-[1fr_0.8fr]"><div className="rounded-3xl border border-border/60 bg-surface-1/80 p-5"><h2 className="mb-4 flex items-center gap-2 font-display text-xl font-bold"><Bot className="h-5 w-5 text-status-ai"/> Diagnósticos</h2><div className="space-y-3">{diag.length?diag.map((d:any,i:number)=><div key={d.id||i} className="rounded-2xl border border-border/45 bg-background/35 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{dash(d.sintoma)}</h3><p className="mt-1 text-xs text-muted-foreground">{dash(d.equipamento)}</p></div><span className={cn("rounded-full border px-2 py-1 text-[10px] font-bold uppercase tracking-[0.14em]",String(d.prioridade).includes("alta")||String(d.prioridade).includes("crit")?"border-rose-400/40 bg-rose-400/10 text-rose-300":"border-amber-400/40 bg-amber-400/10 text-amber-300")}>{dash(d.prioridade)}</span></div><div className="mt-3 grid gap-3 md:grid-cols-2"><List title="Evidências" items={d.evidencias}/><List title="Ações" items={d.acoes_recomendadas}/></div></div>):<EmptyState/>}</div></div><div className="space-y-4"><Panel title="Resumo"><List items={resumo.principais_ocorrencias}/></Panel><Panel title="Prioridades"><List items={resumo.recomendacoes_prioritarias}/></Panel></div></section></div>}
function Card({title,value}:{title:string;value:any}){return <div className="rounded-3xl border border-border/60 bg-surface-1/80 p-5"><div className="text-xs uppercase tracking-[0.16em] text-muted-foreground">{title}</div><div className="mt-3 font-display text-4xl font-bold">{dash(value)}</div></div>}
function Panel({title,children}:{title:string;children:any}){return <div className="rounded-3xl border border-border/60 bg-surface-1/80 p-5"><h2 className="mb-4 font-display text-lg font-bold">{title}</h2>{children}</div>}
function List({title,items}:{title?:string;items:any[]}){return <div>{title&&<div className="mb-2 text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">{title}</div>}<div className="space-y-2">{(items||[]).slice(0,5).map((x:any,i:number)=><div key={i} className="flex gap-2 text-sm text-muted-foreground"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary"/><span>{dash(typeof x==="string"?x:x?.title||x?.desc)}</span></div>)}</div></div>}
