import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, Bell, CheckCircle2, Clock3, Siren, Wrench } from "lucide-react";
import { cn } from "@/lib/utils";
import { dash, EmptyState, LoadingState, periodTitle, useDashboard } from "@/lib/dashboard-api";
export const Route = createFileRoute("/alarms")({ head: () => ({ meta: [{ title: "Alarmes — CAG Expo Center Norte" }] }), component: AlarmsPage });
function AlarmsPage(){const{data,loading,error}=useDashboard();if(loading)return <LoadingState/>;if(error||!data)return <EmptyState message={error||"Sem dados para exibir."}/>;const a=data.alarmes||{};const s=a.summary||{};const timeline=a.timeline||[];return <div className="space-y-5"><section className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><h1 className="font-display text-3xl font-bold">Alarmes</h1><p className="mt-1 text-sm text-muted-foreground">Eventos e recomendações do período {periodTitle(data)}</p></div></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><K title="Ativos" value={s.ativos} icon={<Bell/>}/><K title="Críticos" value={s.criticos} icon={<Siren/>} crit/><K title="Atenção" value={s.atencao} icon={<AlertTriangle/>} warn/><K title="Resolvidos" value={s.resolvidos} icon={<CheckCircle2/>} ok/></section><section className="grid gap-4 xl:grid-cols-[1fr_0.45fr]"><div className="rounded-3xl border border-border/60 bg-surface-1/80 p-5"><h2 className="mb-4 flex items-center gap-2 font-display text-xl font-bold"><Clock3 className="h-5 w-5 text-primary"/>Linha do tempo</h2><div className="space-y-3">{timeline.length?timeline.map((e:any,i:number)=><div key={i} className="rounded-2xl border border-border/45 bg-background/35 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{dash(e.title)}</h3><p className="mt-1 text-xs text-muted-foreground">{dash(e.equipment)} · {dash(e.detail)}</p></div><Tag value={e.severity}/></div></div>):<EmptyState message="Sem alarmes no período."/>}</div></div><div className="space-y-4"><Panel title="Mais recorrentes">{(a.recorrentes||[]).slice(0,5).map((r:any,i:number)=><Row key={i} title={r.title} desc={`${dash(r.count)} ocorrência(s)`}/>)}</Panel><Panel title="Ações recomendadas">{(a.recomendacoes_operacionais||[]).slice(0,5).map((r:any,i:number)=><Row key={i} title={r} icon={<Wrench className="h-4 w-4"/>}/>)}</Panel></div></section></div>}
function K({title,value,icon,crit,warn,ok}:{title:string;value:any;icon:any;crit?:boolean;warn?:boolean;ok?:boolean}){return <div className="rounded-3xl border border-border/60 bg-surface-1/80 p-5"><div className="flex items-center justify-between"><div className="text-xs uppercase tracking-[0.16em] text-muted-foreground">{title}</div><span className={cn("grid h-10 w-10 place-items-center rounded-2xl border",crit?"border-rose-400/40 bg-rose-400/10 text-rose-300":warn?"border-amber-400/40 bg-amber-400/10 text-amber-300":ok?"border-emerald-400/40 bg-emerald-400/10 text-emerald-300":"border-primary/40 bg-primary/10 text-primary")}>{icon}</span></div><div className="mt-3 font-display text-4xl font-bold">{dash(value)}</div></div>}
function Tag({value}:{value:any}){const v=String(value||"").toLowerCase();return <span className={cn("rounded-full border px-2 py-1 text-[10px] font-bold uppercase tracking-[0.14em]",v.includes("crit")||v.includes("alta")?"border-rose-400/40 bg-rose-400/10 text-rose-300":"border-amber-400/40 bg-amber-400/10 text-amber-300")}>{dash(value)}</span>}
function Panel({title,children}:{title:string;children:any}){return <div className="rounded-3xl border border-border/60 bg-surface-1/80 p-5"><h2 className="mb-4 font-display text-lg font-bold">{title}</h2><div className="space-y-3">{children}</div></div>}
function Row({title,desc,icon}:{title:any;desc?:any;icon?:any}){return <div className="rounded-2xl border border-border/45 bg-background/35 p-3"><div className="flex gap-2"><span className="mt-0.5 text-primary">{icon||<AlertTriangle className="h-4 w-4"/>}</span><div><p className="text-sm font-semibold">{dash(title)}</p>{desc&&<p className="mt-1 text-xs text-muted-foreground">{desc}</p>}</div></div></div>}
